plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

relative_links:
  enabled: true
  collections: true

include:
  - index.md


remote_theme: vaibhavvikas/jekyll-theme-minimalistic

navigation:
  - name: Academic
    link: ./index.html

title: Adrienne Ren’s homepage
